// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/krobus00/product-service/internal/model (interfaces: ProductUsecase)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	asynq "github.com/hibiken/asynq"
	auth "github.com/krobus00/auth-service/pb/auth"
	model "github.com/krobus00/product-service/internal/model"
	storage "github.com/krobus00/storage-service/pb/storage"
	nats "github.com/nats-io/nats.go"
	gorm "gorm.io/gorm"
)

// MockProductUsecase is a mock of ProductUsecase interface.
type MockProductUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockProductUsecaseMockRecorder
}

// MockProductUsecaseMockRecorder is the mock recorder for MockProductUsecase.
type MockProductUsecaseMockRecorder struct {
	mock *MockProductUsecase
}

// NewMockProductUsecase creates a new mock instance.
func NewMockProductUsecase(ctrl *gomock.Controller) *MockProductUsecase {
	mock := &MockProductUsecase{ctrl: ctrl}
	mock.recorder = &MockProductUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductUsecase) EXPECT() *MockProductUsecaseMockRecorder {
	return m.recorder
}

// ConsumeEvent mocks base method.
func (m *MockProductUsecase) ConsumeEvent() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumeEvent")
	ret0, _ := ret[0].(error)
	return ret0
}

// ConsumeEvent indicates an expected call of ConsumeEvent.
func (mr *MockProductUsecaseMockRecorder) ConsumeEvent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumeEvent", reflect.TypeOf((*MockProductUsecase)(nil).ConsumeEvent))
}

// Create mocks base method.
func (m *MockProductUsecase) Create(arg0 context.Context, arg1 *model.CreateProductPayload) (*model.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*model.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockProductUsecaseMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProductUsecase)(nil).Create), arg0, arg1)
}

// CreateStream mocks base method.
func (m *MockProductUsecase) CreateStream() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStream")
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateStream indicates an expected call of CreateStream.
func (mr *MockProductUsecaseMockRecorder) CreateStream() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStream", reflect.TypeOf((*MockProductUsecase)(nil).CreateStream))
}

// Delete mocks base method.
func (m *MockProductUsecase) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProductUsecaseMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProductUsecase)(nil).Delete), arg0, arg1)
}

// FindByID mocks base method.
func (m *MockProductUsecase) FindByID(arg0 context.Context, arg1 string) (*model.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0, arg1)
	ret0, _ := ret[0].(*model.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockProductUsecaseMockRecorder) FindByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockProductUsecase)(nil).FindByID), arg0, arg1)
}

// FindByIDs mocks base method.
func (m *MockProductUsecase) FindByIDs(arg0 context.Context, arg1 []string) (model.Products, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDs", arg0, arg1)
	ret0, _ := ret[0].(model.Products)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIDs indicates an expected call of FindByIDs.
func (mr *MockProductUsecaseMockRecorder) FindByIDs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDs", reflect.TypeOf((*MockProductUsecase)(nil).FindByIDs), arg0, arg1)
}

// FindPaginatedIDs mocks base method.
func (m *MockProductUsecase) FindPaginatedIDs(arg0 context.Context, arg1 *model.PaginationPayload) (*model.PaginationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPaginatedIDs", arg0, arg1)
	ret0, _ := ret[0].(*model.PaginationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPaginatedIDs indicates an expected call of FindPaginatedIDs.
func (mr *MockProductUsecaseMockRecorder) FindPaginatedIDs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPaginatedIDs", reflect.TypeOf((*MockProductUsecase)(nil).FindPaginatedIDs), arg0, arg1)
}

// HandleUpdateThumbnailTask mocks base method.
func (m *MockProductUsecase) HandleUpdateThumbnailTask(arg0 context.Context, arg1 *asynq.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleUpdateThumbnailTask", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleUpdateThumbnailTask indicates an expected call of HandleUpdateThumbnailTask.
func (mr *MockProductUsecaseMockRecorder) HandleUpdateThumbnailTask(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleUpdateThumbnailTask", reflect.TypeOf((*MockProductUsecase)(nil).HandleUpdateThumbnailTask), arg0, arg1)
}

// InjectAsynqClient mocks base method.
func (m *MockProductUsecase) InjectAsynqClient(arg0 *asynq.Client) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InjectAsynqClient", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// InjectAsynqClient indicates an expected call of InjectAsynqClient.
func (mr *MockProductUsecaseMockRecorder) InjectAsynqClient(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InjectAsynqClient", reflect.TypeOf((*MockProductUsecase)(nil).InjectAsynqClient), arg0)
}

// InjectAuthClient mocks base method.
func (m *MockProductUsecase) InjectAuthClient(arg0 auth.AuthServiceClient) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InjectAuthClient", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// InjectAuthClient indicates an expected call of InjectAuthClient.
func (mr *MockProductUsecaseMockRecorder) InjectAuthClient(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InjectAuthClient", reflect.TypeOf((*MockProductUsecase)(nil).InjectAuthClient), arg0)
}

// InjectDB mocks base method.
func (m *MockProductUsecase) InjectDB(arg0 *gorm.DB) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InjectDB", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// InjectDB indicates an expected call of InjectDB.
func (mr *MockProductUsecaseMockRecorder) InjectDB(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InjectDB", reflect.TypeOf((*MockProductUsecase)(nil).InjectDB), arg0)
}

// InjectJetstreamClient mocks base method.
func (m *MockProductUsecase) InjectJetstreamClient(arg0 nats.JetStreamContext) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InjectJetstreamClient", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// InjectJetstreamClient indicates an expected call of InjectJetstreamClient.
func (mr *MockProductUsecaseMockRecorder) InjectJetstreamClient(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InjectJetstreamClient", reflect.TypeOf((*MockProductUsecase)(nil).InjectJetstreamClient), arg0)
}

// InjectProductRepo mocks base method.
func (m *MockProductUsecase) InjectProductRepo(arg0 model.ProductRepository) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InjectProductRepo", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// InjectProductRepo indicates an expected call of InjectProductRepo.
func (mr *MockProductUsecaseMockRecorder) InjectProductRepo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InjectProductRepo", reflect.TypeOf((*MockProductUsecase)(nil).InjectProductRepo), arg0)
}

// InjectStorageClient mocks base method.
func (m *MockProductUsecase) InjectStorageClient(arg0 storage.StorageServiceClient) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InjectStorageClient", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// InjectStorageClient indicates an expected call of InjectStorageClient.
func (mr *MockProductUsecaseMockRecorder) InjectStorageClient(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InjectStorageClient", reflect.TypeOf((*MockProductUsecase)(nil).InjectStorageClient), arg0)
}

// Update mocks base method.
func (m *MockProductUsecase) Update(arg0 context.Context, arg1 *model.UpdateProductPayload) (*model.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*model.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockProductUsecaseMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProductUsecase)(nil).Update), arg0, arg1)
}
