apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-worker
  labels:
    app: {{ .Values.app.name }}-worker
    group: {{ .Values.app.group }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-worker
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}-worker
        group: {{ .Values.app.group }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum | trunc 10}}
    spec:
      containers:
        - name: {{ .Values.app.name }}-worker
          image: {{ .Values.app.container.image }}:{{ .Values.app.container.version }}
          imagePullPolicy: "Always"
          command: ["/app/bin/product-service", "worker"]
          ports:
            - containerPort: {{ .Values.app.container.ports.metrics }}
          volumeMounts:
            - name: {{ .Values.app.name }}-config
              mountPath: /app/config.yml
              subPath: config.yml
              readOnly: true
      volumes:
        - name: {{ .Values.app.name }}-config
          configMap:
            name: {{ .Values.app.name }}-configmap
